version: "3.7"

services:
  app:
    build:
      context: .
    env_file:
      - .env
      - .env.db
    restart: on-failure
    command: >
      /wait-for-it.sh db:27017 -- node app.js

  db:
      image: mongo
      ports:
      - "27018:27017"
      env_file:
        - .env.db
      restart: on-failure
      volumes:
      - ./mongo:/var/lib/mongo

  web:
       image: library/nginx:alpine
       ports:
       - "80:80"
       restart: on-failure
       volumes:
       - ./client:/usr/share/nginx/html
       - ./nginx.conf:/etc/nginx/conf.d/default.conf

